services:
  spotube:
    image: lscr.io/linuxserver/spotube:latest
    container_name: spotube
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Container/Spotube/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped